spring.application.name=config
server.port=9999

# ? Configuration avec VOTRE chemin spécifique
spring.cloud.config.server.git.uri=file:///C:/Users/abdelghafour/OneDrive/Bureau/springMBDS/config-repo

# Profil native pour utiliser le système de fichiers
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=file:///C:/Users/abdelghafour/OneDrive/Bureau/springMBDS/config-repo

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always