# Configuration spécifique Account Service
spring.application.name=account
server.port=8081

# Database
spring.datasource.url=jdbc:h2:mem:accountDb
spring.h2.console.enabled=true

# Resilience4J
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.customerService.base-config=default

# Info
info.service.name=Account Service
info.service.description=Manages bank accounts