# Configuration spécifique Customer Service
spring.application.name=customer
server.port=8080

# Database
spring.datasource.url=jdbc:h2:mem:customerDb
spring.h2.console.enabled=true

# Info
info.service.name=Customer Service
info.service.description=Manages customer data