spring.application.name=gateway

# Nouvelle configuration OBLIGATOIRE
spring.config.import=configserver:http://localhost:9999

# Config Client
spring.cloud.config.fail-fast=true
spring.cloud.config.timeout.connect=5000
spring.cloud.config.timeout.read=5000
