spring.application.name=discovery
server.port=8761

# Empêche Eureka Server de s'enregistrer lui-même comme client
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Interface web Eureka
eureka.server.wait-time-in-ms-when-sync-empty=0

management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always